(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const escape = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const state = { page: 'dashboard', products: [], consultations: [], schemes: [], auth: null, dealers: [], options: [] };
  const titles = { dashboard: '业务总览', products: '产品与配置', options: '选配字典', consultations: '咨询订单', schemes: '定制方案', dealers: '经销商管理', assets: '素材上传', admins: '管理员', settings: '系统与安全', catalogAudit: '产品一致性', sources: '来源文档', audit: '操作日志' };
  const roleRank = { viewer: 10, editor: 20, dealer_manager: 30, admin: 40, super_admin: 50 };
  const roleAtLeast = (minimum) => (roleRank[state.auth?.role] || 0) >= (roleRank[minimum] || 999);
  const toast = (message, error = false) => { const el = $('#toast'); el.textContent = message; el.classList.toggle('error-toast', error); el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2400); };
  const api = async (path, options = {}) => {
    const headers = { ...(options.body instanceof FormData ? {} : { 'Content-Type': 'application/json' }), ...(options.headers || {}) };
    if (state.auth?.csrf && ['POST','PATCH','DELETE'].includes(options.method)) headers['X-YADILO-CSRF'] = state.auth.csrf;
    const response = await fetch(`./api${path}`, { ...options, credentials: 'same-origin', headers });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || `请求失败 ${response.status}`);
    return data;
  };
  const fmt = (value) => value ? new Date(String(value).replace(' ', 'T') + (String(value).endsWith('Z') ? '' : 'Z')).toLocaleString('zh-CN', { month:'numeric', day:'numeric', hour:'2-digit', minute:'2-digit' }) : '—';
  const money = (value) => value == null ? '—' : `¥ ${(Number(value) / 100).toLocaleString('zh-CN', { minimumFractionDigits: 0 })}`;
  const statusBadge = (status) => `<span class="badge ${status === 'new' ? 'red' : status === 'closed' ? 'green' : ''}">${({new:'待联系',contacted:'已联系',quoted:'已报价',closed:'已完成',invalid:'无效',draft:'草稿',archived:'已归档'}[status] || status || '—')}</span>`;
  const post = (path, body) => api(path, { method: 'POST', body: JSON.stringify(body) });
  const patch = (path, body) => api(path, { method: 'PATCH', body: JSON.stringify(body) });

  async function boot() {
    const auth = await api('/auth/me'); state.auth = auth;
    if (!auth.authenticated) { $('#loginView').hidden = false; $('#appView').hidden = true; return; }
    $('#loginView').hidden = true; $('#appView').hidden = false; $('#currentUser').textContent = `${auth.username} · ${auth.role}`;
    document.querySelectorAll('[data-role]').forEach((item) => { item.hidden = !roleAtLeast(item.dataset.role); });
    bindNavigation(); await navigate('dashboard');
  }

  $('#loginForm').addEventListener('submit', async (event) => {
    event.preventDefault(); const form = new FormData(event.currentTarget); const error = $('#loginError');
    try { const result = await post('/auth/login', { username: form.get('username'), password: form.get('password') }); state.auth = { authenticated:true, username:result.username, role:result.role, csrf:result.csrf }; error.textContent = ''; await boot(); }
    catch (err) { error.textContent = err.message; }
  });
  $('#logoutButton').addEventListener('click', async () => { await post('/auth/logout', {}); location.reload(); });
  function bindNavigation() { if ($('#nav').dataset.bound) return; $('#nav').dataset.bound = '1'; $('#nav').addEventListener('click', (event) => { const button = event.target.closest('[data-page]'); if (button) navigate(button.dataset.page); }); }
  async function navigate(page) { state.page = page; document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.page === page)); $('#pageTitle').textContent = titles[page]; try { await renderPage(page); } catch (err) { $('#content').innerHTML = `<div class="panel"><div class="empty">${escape(err.message)}</div></div>`; } }
  async function renderPage(page) {
    if (page === 'dashboard') return renderDashboard(await api('/dashboard'));
    if (page === 'products') return renderProducts(await api('/products'));
    if (page === 'options') return renderOptions(await api('/options'));
    if (page === 'consultations') return renderConsultations(await api('/consultations'));
    if (page === 'schemes') return renderSchemes(await api('/schemes'));
    if (page === 'dealers') return renderDealers(await api('/dealers'));
    if (page === 'assets') return renderAssets();
    if (page === 'admins') return renderAdmins();
    if (page === 'settings') return renderSettings();
    if (page === 'catalogAudit') return renderCatalogAudit(await api('/catalog-audit'));
    if (page === 'sources') return renderSources(await api('/sources'));
    if (page === 'audit') return renderAudit(await api('/audit'));
  }

  function renderDashboard(data) {
    $('#leadBadge').classList.toggle('show', Number(data.new_consultations) > 0);
    $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">01 / OPERATIONS BOARD</span><h3>今天，先看需要跟进的事情</h3><p>产品目录、配置规则和客户意向在这里汇总。</p></div><button class="button primary-small" data-go="consultations">查看咨询订单</button></div>
      <div class="metric-grid"><div class="metric"><small>在售产品</small><strong>${data.products}</strong><em>数据库产品主档</em></div><div class="metric"><small>可配置产品</small><strong>${data.configurable}</strong><em>K80 / D90</em></div><div class="metric"><small>待处理咨询</small><strong>${data.new_consultations}</strong><em>需要门店跟进</em></div><div class="metric"><small>保存方案</small><strong>${data.schemes}</strong><em>来自前台配置器</em></div><div class="metric"><small>价格规则</small><strong>${data.price_rules}</strong><em>官方资料已入库</em></div></div>
      <div class="cmfp-strip"><span class="cmfp-label">CMFP / DESIGN CONTROL</span><span><b>C</b> 色彩</span><span><b>M</b> 材料</span><span><b>F</b> 表面处理</span><span><b>P</b> 图形纹理</span><button class="text-button" data-go="sources">查看设计手册 ↗</button></div>
      <div class="panel"><div class="panel-head"><h3>最近咨询</h3><small>按提交时间倒序</small></div><div class="table-wrap">${consultationTable(data.recent_consultations || [])}</div></div>`;
    $('#content').querySelector('[data-go]')?.addEventListener('click', () => navigate('consultations'));
  }
  function consultationTable(items) { if (!items.length) return '<div class="empty">还没有咨询记录</div>'; return `<table class="data-table"><thead><tr><th>客户</th><th>电话</th><th>产品</th><th>状态</th><th>提交时间</th></tr></thead><tbody>${items.map((item) => `<tr><td>${escape(item.customer_name)}</td><td>${escape(item.phone)}</td><td>${escape(item.product_label || item.product || '未指定')}</td><td>${statusBadge(item.status)}</td><td>${fmt(item.created_at)}</td></tr>`).join('')}</tbody></table>`; }

  function renderProducts(items) {
    state.products = items; $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">02 / PRODUCT SYSTEM</span><h3>产品与配置主档</h3><p>按手册的组件拆解维护产品：门套、门框、结构板、外饰面与五金。</p></div><div class="toolbar"><input class="search" id="productSearch" placeholder="搜索产品名 / 配置键" /><button class="button" id="refreshProducts">刷新</button></div></div><div class="component-rail"><span><i class="component-line"></i>门套结构</span><span><i class="component-line"></i>门框结构</span><span><i class="component-line coral"></i>外饰面板</span><span><i class="component-line"></i>正背面结构板</span><span><i class="component-line teal"></i>内外五金</span></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>产品</th><th>产品键</th><th>产品线</th><th>配置入口</th><th>默认门型</th><th>状态</th><th></th></tr></thead><tbody id="productRows">${productRows(items)}</tbody></table></div></div>`;
    $('#productSearch').addEventListener('input', (event) => { const q = event.target.value.toLowerCase(); $('#productRows').innerHTML = productRows(items.filter((item) => `${item.name} ${item.product_key} ${item.configurator_key || ''}`.toLowerCase().includes(q))); });
    $('#refreshProducts').addEventListener('click', () => navigate('products'));
    $('#productRows').addEventListener('click', async (event) => { const button = event.target.closest('[data-product-action]'); if (!button) return; try { if (button.dataset.productAction === 'toggle') { await patch(`/products?id=${button.dataset.id}`, { active: button.dataset.active !== '1' }); toast('产品状态已更新'); navigate('products'); } else showProduct(button.dataset.id); } catch (err) { toast(err.message, true); } });
  }
  function productRows(items) { return items.map((item) => `<tr><td><b>${escape(item.name)}</b><br><small>${escape(item.catalog_serial || item.style || '')}</small></td><td>${escape(item.product_key)}</td><td>${escape(item.series_name)}</td><td>${item.configurator_key ? `<span class="badge green">${escape(item.configurator_key)}</span>` : '<span class="badge">目录</span>'}</td><td>${escape(item.default_type_name || '—')}</td><td>${item.active ? '<span class="badge green">启用</span>' : '<span class="badge red">停用</span>'}</td><td><button class="button" data-product-action="detail" data-id="${item.id}">编辑配置</button> <button class="button ${item.active ? 'danger' : ''}" data-product-action="toggle" data-id="${item.id}" data-active="${item.active ? 1 : 0}">${item.active ? '停用' : '启用'}</button></td></tr>`).join('') || '<tr><td colspan="7" class="empty">没有匹配产品</td></tr>'; }

  function input(label, value, key, type = 'text') { return `<label>${label}<input type="${type}" data-field="${key}" value="${escape(value)}"></label>`; }
  function select(label, key, options, value) { return `<label>${label}<select data-field="${key}">${options.map((item) => `<option value="${escape(item.value)}" ${String(item.value) === String(value) ? 'selected' : ''}>${escape(item.label)}</option>`).join('')}</select></label>`; }
  function drawerShell(content, width = '') { const backdrop = document.createElement('div'); backdrop.className = 'drawer-backdrop'; backdrop.innerHTML = `<aside class="drawer" ${width ? `style="width:${width}"` : ''}><button class="close" type="button" data-drawer-close aria-label="关闭详情">×</button>${content}</aside>`; document.body.append(backdrop); const close = () => backdrop.remove(); backdrop.querySelector('[data-drawer-close]').addEventListener('click', close); backdrop.addEventListener('click', (event) => { if (event.target === backdrop) close(); }); return backdrop; }
  function drawerButton(label, action, id = '') { return `<button class="button" data-drawer-action="${action}" ${id ? `data-id="${id}"` : ''}>${label}</button>`; }

  async function showProduct(id) {
    const [item, allTypes] = await Promise.all([api(`/products/detail?id=${id}`), api('/door-types')]);
    const typeRows = allTypes.map((type) => { const current = item.types.find((entry) => entry.id === type.id); return `<div class="type-block"><div class="rule-row type-rule" data-type-id="${type.id}"><label class="check-line"><input type="checkbox" data-type-enabled ${current ? 'checked' : ''}>${escape(type.name)}</label><input type="number" data-dim="width_min_mm" value="${current?.width_min_mm || type.width_min_mm || 900}" placeholder="宽最小"><input type="number" data-dim="width_default_mm" value="${current?.width_default_mm || type.width_default_mm || 1000}" placeholder="宽默认"><input type="number" data-dim="width_max_mm" value="${current?.width_max_mm || type.width_max_mm || 1300}" placeholder="宽最大"><input type="number" data-dim="height_min_mm" value="${current?.height_min_mm || type.height_min_mm || 2200}" placeholder="高最小"><input type="number" data-dim="height_default_mm" value="${current?.height_default_mm || type.height_default_mm || 2400}" placeholder="高默认"><input type="number" data-dim="height_max_mm" value="${current?.height_max_mm || type.height_max_mm || 3000}" placeholder="高最大"><label class="check-line"><input type="radio" name="defaultDoorType" data-type-default ${current?.is_default ? 'checked' : ''}>默认</label></div><div class="engineering-grid" data-engineering-for="${type.id}"><span>工程约束</span><input type="number" data-eng="panel_thickness_mm" placeholder="T1 面板厚" value="${current?.panel_thickness_mm ?? ''}"><input type="number" data-eng="door_depth_mm" placeholder="T2 门体深" value="${current?.door_depth_mm ?? ''}"><input type="number" data-eng="frame_depth_mm" placeholder="T3 门框深" value="${current?.frame_depth_mm ?? ''}"><input type="number" data-eng="casing_depth_mm" placeholder="T4 门套深" value="${current?.casing_depth_mm ?? ''}"><input type="number" data-eng="lock_gap_mm" placeholder="WR 锁孔间隙" value="${current?.lock_gap_mm ?? ''}"><input type="number" data-eng="lock_height_mm" placeholder="HR 锁孔高度" value="${current?.lock_height_mm ?? ''}"></div></div>`; }).join('');
    const groups = [...new Set(item.all_options.map((option) => option.group_name))];
    const optionRows = item.all_options.map((option) => { const current = item.options.find((entry) => entry.id === option.id); return `<div class="option-row" data-option-id="${option.id}"><label class="check-line"><input type="checkbox" data-option-enabled ${current ? 'checked' : ''}><span>${escape(option.group_name)} / ${escape(option.name)}</span></label><input type="number" data-option-price placeholder="价格覆盖（分）" value="${current?.price_override_cents ?? ''}"><label class="check-line"><input type="checkbox" data-option-default ${current?.is_default ? 'checked' : ''}>默认</label><label class="check-line"><input type="checkbox" data-option-required ${current?.is_required ? 'checked' : ''}>必选</label><select data-option-types multiple size="2" aria-label="兼容门型"><option value="">全部支持门型（留空）</option>${allTypes.map((type) => `<option value="${type.id}" ${current?.door_type_ids?.includes(type.id) ? 'selected' : ''}>${escape(type.name)}</option>`).join('')}</select></div>`; }).join('');
    const attrRows = item.attributes.map((attr) => `<div class="attribute-row"><input data-attr-key value="${escape(attr.attribute_key)}"><select data-attr-type><option ${attr.value_type === 'text' ? 'selected' : ''}>text</option><option ${attr.value_type === 'number' ? 'selected' : ''}>number</option><option ${attr.value_type === 'boolean' ? 'selected' : ''}>boolean</option><option ${attr.value_type === 'json' ? 'selected' : ''}>json</option></select><input data-attr-value value="${escape(attr.attribute_value)}"><button class="button" data-remove-row>删除</button></div>`).join('');
    const priceRows = item.prices.map((price) => `<div class="price-row" data-price-id="${price.id}"><span>${escape(price.price_kind)}</span><input data-price-amount type="number" value="${price.amount_cents ?? ''}" placeholder="金额（分）"><input data-price-unit value="${escape(price.unit || 'each')}" placeholder="单位"><input data-price-note value="${escape(price.notes || '')}" placeholder="备注"><button class="button" data-drawer-action="save-price">保存</button></div>`).join('') || '<div class="empty">暂无价格规则</div>';
    const assetRows = item.assets.map((asset) => `<div class="asset-row"><span>${escape(asset.asset_role)}</span><code>${escape(asset.file_path)}</code><span>${asset.is_primary ? '主资产' : ''}</span></div>`).join('') || '<div class="empty">暂无资产引用</div>';
    const backdrop = drawerShell(`<p class="eyebrow">PRODUCT / ${escape(item.configurator_key || 'CATALOG')}</p><h3>${escape(item.name)}</h3><p class="muted">${escape(item.series_name)} · ${escape(item.product_key)}</p>
      <section class="drawer-section"><div class="drawer-section-head"><h4>基础资料</h4>${drawerButton('保存基础资料','save-profile')}</div><div class="edit-grid">${input('产品名称', item.name, 'name')}${input('英文名称', item.english_name, 'english_name')}${input('产品编号', item.catalog_serial, 'catalog_serial')}${input('产品风格', item.style, 'style')}${input('产品线', item.line_code, 'line_code')}${input('configurator key', item.configurator_key, 'configurator_key')}${input('缩略图路径', item.thumbnail_path, 'thumbnail_path')}<label class="check-line"><input type="checkbox" data-field="active" ${item.active ? 'checked' : ''}>启用前台展示</label></div></section>
      <section class="drawer-section"><div class="drawer-section-head"><h4>支持门型与尺寸（mm）</h4>${drawerButton('保存门型','save-types')}</div><p class="muted">勾选门型，填写最小 / 默认 / 最大宽高，并指定唯一默认门型。</p><div class="rule-head">门型 / 宽最小 / 宽默认 / 宽最大 / 高最小 / 高默认 / 高最大 / 默认</div><div id="typeRules">${typeRows}</div></section>
      <section class="drawer-section"><div class="drawer-section-head"><h4>选配兼容</h4>${drawerButton('保存选配','save-options')}</div><p class="muted">停用选配不会出现在这里；空门型表示兼容产品全部门型。</p><div id="optionRules">${optionRows}</div></section>
      <section class="drawer-section"><div class="drawer-section-head"><h4>产品属性</h4><div>${drawerButton('新增属性','add-attribute')}${drawerButton('保存属性','save-attributes')}</div></div><div id="attributeRows">${attrRows}</div></section>
      <section class="drawer-section"><div class="drawer-section-head"><h4>价格规则</h4>${drawerButton('新增规则','add-price')}</div><div id="priceRows">${priceRows}</div><div id="newPriceRow" hidden></div></section>
      <section class="drawer-section"><div class="drawer-section-head"><h4>模型、纹理与实拍资产</h4></div><div id="assetRows">${assetRows}</div><div class="edit-grid asset-form">${input('资产角色','texture','asset_role')}${input('文件路径','','file_path')}${input('选配 ID（可选）','','option_id','number')}<label class="check-line"><input type="checkbox" data-field="is_primary">设为该角色主资产</label>${drawerButton('新增资产','save-asset')}</div></section>`, 'min(1040px,94vw)');
    bindProductDrawer(backdrop, item, allTypes);
  }

  function fieldValue(root, key) { const el = root.querySelector(`[data-field="${key}"]`); return el?.type === 'checkbox' ? el.checked : (el?.value ?? ''); }
  function collectTypes(root) { return [...root.querySelectorAll('.type-rule')].filter((row) => $('[data-type-enabled]', row)?.checked).map((row) => { const engineering = root.querySelector(`[data-engineering-for="${row.dataset.typeId}"]`); return { door_type_id: Number(row.dataset.typeId), is_default: $('[data-type-default]', row)?.checked, ...Object.fromEntries([...row.querySelectorAll('[data-dim]')].map((input) => [input.dataset.dim, Number(input.value)])), ...Object.fromEntries([...engineering.querySelectorAll('[data-eng]')].filter((input) => input.value !== '').map((input) => [input.dataset.eng, Number(input.value)])) }; }); }
  function collectOptions(root) { return [...root.querySelectorAll('.option-row')].filter((row) => $('[data-option-enabled]', row)?.checked).map((row) => ({ option_id: Number(row.dataset.optionId), is_default: $('[data-option-default]', row)?.checked, is_required: $('[data-option-required]', row)?.checked, price_override_cents: $('[data-option-price]', row)?.value === '' ? null : Number($('[data-option-price]', row).value), door_type_ids: [...($('[data-option-types]', row)?.selectedOptions || [])].map((option) => Number(option.value)).filter(Boolean) })); }
  function collectAttributes(root) { return [...root.querySelectorAll('.attribute-row')].map((row) => ({ attribute_key: $('[data-attr-key]', row)?.value.trim(), attribute_value: $('[data-attr-value]', row)?.value, value_type: $('[data-attr-type]', row)?.value })).filter((item) => item.attribute_key); }
  function bindProductDrawer(backdrop, item) {
    const drawer = $('.drawer', backdrop);
    drawer.addEventListener('click', async (event) => {
      if (event.target.closest('[data-remove-row]')) { event.target.closest('.attribute-row')?.remove(); return; }
      const button = event.target.closest('[data-drawer-action]'); if (!button) return;
      try {
        const action = button.dataset.drawerAction;
        if (action === 'save-profile') await patch(`/products/profile?id=${item.id}`, { name:fieldValue(drawer,'name'), english_name:fieldValue(drawer,'english_name'), catalog_serial:fieldValue(drawer,'catalog_serial'), style:fieldValue(drawer,'style'), line_code:fieldValue(drawer,'line_code'), configurator_key:fieldValue(drawer,'configurator_key'), thumbnail_path:fieldValue(drawer,'thumbnail_path'), active:fieldValue(drawer,'active') });
        if (action === 'save-types') await post('/products/types', { product_id:item.id, types:collectTypes(drawer) });
        if (action === 'save-options') await post('/products/options', { product_id:item.id, options:collectOptions(drawer) });
        if (action === 'save-attributes') await post('/products/attributes', { product_id:item.id, attributes:collectAttributes(drawer) });
        if (action === 'add-attribute') { $('#attributeRows', drawer).insertAdjacentHTML('beforeend', '<div class="attribute-row"><input data-attr-key placeholder="属性键"><select data-attr-type><option>text</option><option>number</option><option>boolean</option><option>json</option></select><input data-attr-value placeholder="属性值"><button class="button" data-remove-row>删除</button></div>'); return; }
        if (action === 'add-price') { $('#newPriceRow', drawer).hidden = false; $('#newPriceRow', drawer).innerHTML = `<div class="price-row new-price"><select data-new-price-kind><option value="base_area">基础面积价</option><option value="finish_area">饰面面积价</option><option value="option">选配价</option><option value="fixed">固定价</option><option value="surcharge">附加费</option><option value="formula">公式</option></select><input data-new-price-amount type="number" placeholder="金额（分）"><input data-new-price-unit value="each" placeholder="单位"><input data-new-price-note placeholder="备注"><button class="button primary-small" data-drawer-action="save-new-price">保存</button></div>`; return; }
        if (action === 'save-price') { const row = button.closest('.price-row'); await patch(`/price-rules?id=${row.dataset.priceId}`, { amount_cents: $('[data-price-amount]', row).value === '' ? null : Number($('[data-price-amount]', row).value), unit:$('[data-price-unit]', row).value, notes:$('[data-price-note]', row).value }); }
        if (action === 'save-new-price') { const row = button.closest('.price-row'); await post('/price-rules', { product_id:item.id, price_kind:$('[data-new-price-kind]', row).value, amount_cents:$('[data-new-price-amount]', row).value === '' ? null : Number($('[data-new-price-amount]', row).value), unit:$('[data-new-price-unit]', row).value, notes:$('[data-new-price-note]', row).value }); $('#newPriceRow', drawer).hidden = true; }
        if (action === 'save-asset') { await post('/assets', { product_id:item.id, asset_role:fieldValue(drawer,'asset_role'), file_path:fieldValue(drawer,'file_path'), option_id:fieldValue(drawer,'option_id') ? Number(fieldValue(drawer,'option_id')) : null, is_primary:fieldValue(drawer,'is_primary') }); }
        if (action === 'remove-row') { button.closest('.attribute-row')?.remove(); return; }
        if (action.startsWith('save')) { toast('已保存，重新打开详情可核对数据库结果'); }
      } catch (err) { toast(err.message, true); }
    });
  }

  function renderOptions(items) { const groups = [...new Set(items.map((item) => item.group_name))]; $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">03 / CMFP DICTIONARY</span><h3>选配字典</h3><p>按色彩、材料、表面处理工艺与图形纹理管理前台定制字段。</p></div><div class="toolbar"><select class="select" id="optionGroup"><option value="">全部选配组</option>${groups.map((group) => `<option>${escape(group)}</option>`).join('')}</select></div></div><div class="cmfp-tabs"><button class="cmfp-tab active">C <small>色彩</small></button><button class="cmfp-tab">M <small>材料</small></button><button class="cmfp-tab">F <small>表面处理</small></button><button class="cmfp-tab">P <small>图形纹理</small></button></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>分组</th><th>键</th><th>名称</th><th>说明</th><th>价格</th><th>单位</th><th>状态</th><th></th></tr></thead><tbody id="optionRows">${optionRows(items)}</tbody></table></div></div>`;
    $('#optionGroup').addEventListener('change', (event) => { const value = event.target.value; $('#optionRows').innerHTML = optionRows(value ? items.filter((item) => item.group_name === value) : items); });
    $('#optionRows').addEventListener('click', (event) => { const button = event.target.closest('[data-option-edit]'); if (button) showOption(items.find((item) => String(item.id) === button.dataset.optionEdit)); });
  }
  function optionRows(items) { return items.map((item) => `<tr><td>${escape(item.group_name)}</td><td><code>${escape(item.option_key)}</code></td><td>${escape(item.name)}</td><td>${escape(item.note || '')}</td><td>${money(item.price_cents)}</td><td>${escape(item.unit)}</td><td>${item.active ? '<span class="badge green">启用</span>' : '<span class="badge red">停用</span>'}</td><td><button class="button" data-option-edit="${item.id}">编辑</button></td></tr>`).join('') || '<tr><td colspan="8" class="empty">暂无选配</td></tr>'; }
  function showOption(item) { if (!item) return; const backdrop = drawerShell(`<p class="eyebrow">OPTION / ${escape(item.group_code)}</p><h3>${escape(item.name)}</h3><p class="muted"><code>${escape(item.option_key)}</code> · ${escape(item.group_name)}</p><div class="edit-grid option-edit-form">${input('名称',item.name,'name')}${input('价格（分）',item.price_cents,'price_cents','number')}${input('单位',item.unit,'unit')}<label>说明<textarea data-field="note">${escape(item.note || '')}</textarea></label><label class="check-line"><input type="checkbox" data-field="active" ${item.active ? 'checked' : ''}>启用</label></div><div class="save-bar">${drawerButton('保存','save-option')}</div>`, 'min(580px,88vw)'); $('.drawer', backdrop).addEventListener('click', async (event) => { const button = event.target.closest('[data-drawer-action="save-option"]'); if (!button) return; try { await patch(`/options?id=${item.id}`, { name:fieldValue(backdrop,'name'), note:fieldValue(backdrop,'note'), price_cents:Number(fieldValue(backdrop,'price_cents')), unit:fieldValue(backdrop,'unit'), active:fieldValue(backdrop,'active') }); backdrop.remove(); toast('选配字典已更新'); navigate('options'); } catch (err) { toast(err.message, true); } }); }

  async function renderConsultations(items) { state.consultations = items; $('#content').innerHTML = `<div class="page-head"><div><h3>客户咨询订单</h3><p>前台提交的客户信息、定制配置和下单字段统一进入这里。</p></div><div class="toolbar"><select class="select" id="leadStatus"><option value="">全部状态</option><option value="new">待联系</option><option value="contacted">已联系</option><option value="quoted">已报价</option><option value="closed">已完成</option><option value="invalid">无效</option></select></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>客户</th><th>电话</th><th>城市</th><th>产品</th><th>状态</th><th>提交时间</th><th></th></tr></thead><tbody id="leadRows">${leadRows(items)}</tbody></table></div></div>`; $('#leadStatus').addEventListener('change', async (event) => { const filtered = event.target.value ? await api(`/consultations?status=${event.target.value}`) : await api('/consultations'); $('#leadRows').innerHTML = leadRows(filtered); }); $('#leadRows').addEventListener('change', async (event) => { const select = event.target.closest('[data-lead-status]'); if (!select) return; try { await patch(`/consultations?id=${select.dataset.id}`, { status: select.value }); toast('咨询状态已更新'); } catch (err) { toast(err.message, true); } }); $('#leadRows').addEventListener('click', (event) => { const button = event.target.closest('[data-lead-detail]'); if (button) showConsultation(state.consultations.find((item) => String(item.id) === button.dataset.leadDetail)); }); }
  function leadRows(items) { return items.map((item) => `<tr><td><b>${escape(item.customer_name)}</b><br><small>${escape(item.message || '')}</small></td><td>${escape(item.phone)}</td><td>${escape(item.city || '—')}</td><td>${escape(item.product_label || item.product || '未指定')}</td><td><select class="select" data-lead-status data-id="${item.id}"><option value="new" ${item.status==='new'?'selected':''}>待联系</option><option value="contacted" ${item.status==='contacted'?'selected':''}>已联系</option><option value="quoted" ${item.status==='quoted'?'selected':''}>已报价</option><option value="closed" ${item.status==='closed'?'selected':''}>已完成</option><option value="invalid" ${item.status==='invalid'?'selected':''}>无效</option></select></td><td>${fmt(item.created_at)}</td><td><button class="button" data-lead-detail="${item.id}">查看配置</button></td></tr>`).join('') || '<tr><td colspan="7" class="empty">没有咨询记录</td></tr>'; }
  function showConsultation(item) { if (!item) return; const backdrop = drawerShell(`<p class="eyebrow">CONSULTATION / ${escape(item.source || 'website')}</p><h3>${escape(item.customer_name)} · ${escape(item.phone)}</h3><p class="muted">${escape(item.city || '未填写城市')} · ${fmt(item.created_at)} · ${escape(item.product_label || item.product || '未指定')}</p><div class="detail-list"><div><dt>系列</dt><dd>${escape(item.series || '—')}</dd></div><div><dt>状态</dt><dd>${statusBadge(item.status)}</dd></div><div><dt>留言</dt><dd>${escape(item.message || '—')}</dd></div></div><h4>配置 JSON</h4><pre class="json-box">${escape(JSON.stringify(item.config || {}, null, 2))}</pre><h4>下单字段</h4><pre class="json-box">${escape(JSON.stringify(item.order_payload || {}, null, 2))}</pre><div class="save-bar"><button class="button" data-copy-detail>复制下单 JSON</button></div>`, 'min(760px,90vw)'); $('.drawer', backdrop).addEventListener('click', async (event) => { if (event.target.closest('[data-copy-detail]')) { await navigator.clipboard?.writeText(JSON.stringify(item.order_payload || {}, null, 2)); toast('下单 JSON 已复制'); } }); }

  function renderSchemes(items) { state.schemes = items; $('#content').innerHTML = `<div class="page-head"><div><h3>定制方案</h3><p>来自前台配置器的配置快照、下单字段和 AI 场景图。</p></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>方案</th><th>产品</th><th>系列</th><th>状态</th><th>更新时间</th><th></th></tr></thead><tbody id="schemeRows">${items.map((item) => `<tr><td><b>${escape(item.title)}</b><br><small>${escape(item.external_id)}</small></td><td>${escape(item.product_label || item.product || '—')}</td><td>${escape(item.series || '—')}</td><td><select class="select" data-scheme-status data-id="${item.id}"><option value="draft" ${item.status==='draft'?'selected':''}>草稿</option><option value="quoted" ${item.status==='quoted'?'selected':''}>已报价</option><option value="archived" ${item.status==='archived'?'selected':''}>已归档</option></select></td><td>${fmt(item.updated_at)}</td><td><button class="button" data-scheme-detail="${item.id}">查看方案</button></td></tr>`).join('') || '<tr><td colspan="6" class="empty">暂无保存方案</td></tr>'}</tbody></table></div></div>`; $('#schemeRows').addEventListener('change', async (event) => { const select = event.target.closest('[data-scheme-status]'); if (!select) return; try { await patch(`/schemes/status?id=${select.dataset.id}`, { status:select.value }); toast('方案状态已更新'); } catch (err) { toast(err.message, true); } }); $('#schemeRows').addEventListener('click', (event) => { const button = event.target.closest('[data-scheme-detail]'); if (button) showScheme(button.dataset.schemeDetail); }); }
  async function showScheme(id) { const item = await api(`/schemes/detail?id=${id}`); const scenes = Array.isArray(item.ai_scenes) ? item.ai_scenes : []; const sceneMarkup = scenes.map((scene) => scene.url ? `<img class="scheme-scene-thumb" src="${escape(scene.url)}" alt="AI 场景">` : `<span class="badge">${escape(scene.message || scene.status || '无图片')}</span>`).join('') || '<div class="empty">暂无 AI 场景图</div>'; drawerShell(`<p class="eyebrow">SCHEME / ${escape(item.series || '')}</p><h3>${escape(item.title)}</h3><p class="muted">${escape(item.product_label || item.product || '')} · ${fmt(item.updated_at)}</p><h4>AI 场景</h4><div class="scheme-scene-grid">${sceneMarkup}</div><h4>配置快照</h4><pre class="json-box">${escape(JSON.stringify(item.config, null, 2))}</pre><h4>下单字段</h4><pre class="json-box">${escape(JSON.stringify(item.order_payload, null, 2))}</pre>`); }
  const dealerStatus = { pending: '待审核', active: '合作中', suspended: '已暂停', closed: '已关闭' };
  const dealerLevel = { standard: '标准', silver: '银牌', gold: '金牌', strategic: '战略' };
  const roleLabels = { viewer: '只读', editor: '编辑', dealer_manager: '经销商经理', admin: '管理员', super_admin: '超级管理员' };
  const dealerForm = (item = {}) => `<div class="edit-grid"><label>经销商编码<input data-field="dealer_code" value="${escape(item.dealer_code || '')}" placeholder="例如 BJ-001" ${item.id ? 'disabled' : ''}></label>${input('经销商名称', item.name, 'name')}${input('联系人', item.contact_name, 'contact_name')}${input('电话', item.phone, 'phone')}${input('邮箱', item.email, 'email')}${input('区域', item.region, 'region')}${input('地址', item.address, 'address')}<label>等级<select data-field="level">${Object.entries(dealerLevel).map(([value, label]) => `<option value="${value}" ${item.level === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label><label>状态<select data-field="status">${Object.entries(dealerStatus).map(([value, label]) => `<option value="${value}" ${item.status === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label><label>备注<textarea data-field="notes">${escape(item.notes || '')}</textarea></label></div>`;
  function renderDealers(items) {
    state.dealers = items;
    $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">08 / PARTNER NETWORK</span><h3>经销商管理</h3><p>维护经销商主档、合作等级和账号归属。</p></div><div class="toolbar">${drawerButton('新增经销商', 'new-dealer')}</div></div><div class="metric-grid compact-metrics"><div class="metric"><small>全部经销商</small><strong>${items.length}</strong><em>主档记录</em></div><div class="metric"><small>合作中</small><strong>${items.filter((item) => item.status === 'active').length}</strong><em>可分配账号</em></div><div class="metric"><small>已暂停</small><strong>${items.filter((item) => item.status === 'suspended').length}</strong><em>需要复核</em></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>编码</th><th>经销商</th><th>联系人</th><th>区域</th><th>等级</th><th>状态</th><th>账号</th><th></th></tr></thead><tbody id="dealerRows">${items.map((item) => `<tr><td><code>${escape(item.dealer_code)}</code></td><td><b>${escape(item.name)}</b><br><small>${escape(item.phone || item.email || '')}</small></td><td>${escape(item.contact_name || '—')}</td><td>${escape(item.region || '—')}</td><td>${dealerLevel[item.level] || item.level}</td><td>${statusBadge(item.status === 'active' ? 'closed' : item.status)} ${escape(dealerStatus[item.status] || '')}</td><td>${item.user_count || 0}</td><td><button class="button" data-dealer-action="edit" data-id="${item.id}">编辑</button></td></tr>`).join('') || '<tr><td colspan="8" class="empty">暂无经销商</td></tr>'}</tbody></table></div></div>`;
    $('#content').querySelector('[data-drawer-action="new-dealer"]')?.addEventListener('click', () => showDealer());
    $('#dealerRows').addEventListener('click', (event) => { const button = event.target.closest('[data-dealer-action="edit"]'); if (button) showDealer(state.dealers.find((item) => String(item.id) === button.dataset.id)); });
  }
  function showDealer(item = null) {
    const backdrop = drawerShell(`<p class="eyebrow">DEALER / PARTNER NETWORK</p><h3>${item ? '编辑经销商' : '新增经销商'}</h3><p class="muted">经销商资料会影响后台账号归属。</p>${dealerForm(item || {})}<div class="save-bar"><button class="button primary-small" data-drawer-action="save-dealer">保存经销商</button></div>`, 'min(680px,90vw)');
    $('.drawer', backdrop).addEventListener('click', async (event) => { if (!event.target.closest('[data-drawer-action="save-dealer"]')) return; try { const drawer = $('.drawer', backdrop); const payload = Object.fromEntries([...drawer.querySelectorAll('[data-field]')].map((el) => [el.dataset.field, el.type === 'checkbox' ? el.checked : el.value])); if (item) await patch(`/dealers?id=${item.id}`, payload); else await post('/dealers', payload); backdrop.remove(); toast('经销商资料已保存'); navigate('dealers'); } catch (err) { toast(err.message, true); } });
  }
  async function renderAssets() {
    const [products, options, assets] = await Promise.all([api('/products'), api('/options'), api('/assets')]);
    state.products = products; state.options = options;
    $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">09 / ASSET LIBRARY</span><h3>素材上传</h3><p>上传产品纹理、门型渲染图和选配素材，文件会写入受控上传目录并登记资产引用。</p></div></div><div class="detail-grid"><div class="panel"><div class="panel-head"><h3>上传图片</h3><small>JPG / PNG / WEBP / GIF · 最大 12MB</small></div><form id="assetUploadForm" class="upload-form"><label>关联产品<select name="product_id" id="assetProduct" required><option value="">选择产品</option>${products.map((item) => `<option value="${item.id}">${escape(item.name)} · ${escape(item.product_key)}</option>`).join('')}</select></label><label>关联选配（可选）<select name="option_id"><option value="">不关联选配</option>${options.map((item) => `<option value="${item.id}">${escape(item.group_name)} / ${escape(item.name)}</option>`).join('')}</select></label><label>资产角色<select name="asset_role"><option value="texture">纹理贴图</option><option value="door-render">门型渲染图</option><option value="thumbnail">缩略图</option><option value="hardware">五金素材</option><option value="casing">门套素材</option><option value="model-preview">模型预览</option></select></label><label>图片文件<input type="file" name="file" accept="image/jpeg,image/png,image/webp,image/gif" required></label><label class="check-line"><input type="checkbox" name="is_primary">设为该角色主资产</label><div id="assetPreview" class="asset-preview"><span>选择图片后预览</span></div><div class="save-bar"><button class="button primary-small" type="submit">上传并登记</button></div><p id="assetUploadError" class="error"></p></form></div><div class="panel"><div class="panel-head"><h3>最近资产</h3><small>${assets.length} 条</small></div><div class="table-wrap"><table class="data-table"><thead><tr><th>产品</th><th>角色</th><th>文件</th><th>主资产</th></tr></thead><tbody>${assets.map((item) => `<tr><td>${escape(item.product_name || '—')}</td><td>${escape(item.asset_role)}</td><td><code>${escape(item.file_path)}</code></td><td>${item.is_primary ? '<span class="badge green">是</span>' : '—'}</td></tr>`).join('') || '<tr><td colspan="4" class="empty">暂无资产</td></tr>'}</tbody></table></div></div></div>`;
    const form = $('#assetUploadForm'); form.file = $('input[type="file"]', form); form.file.addEventListener('change', () => { const file = form.file.files[0]; $('#assetPreview').innerHTML = file ? `<img src="${URL.createObjectURL(file)}" alt="待上传预览"><span>${escape(file.name)}</span>` : '<span>选择图片后预览</span>'; });
    form.addEventListener('submit', async (event) => { event.preventDefault(); const error = $('#assetUploadError'); error.textContent = ''; try { const data = new FormData(form); await api('/assets/upload', { method: 'POST', body: data }); toast('图片已上传并登记'); await renderAssets(); } catch (err) { error.textContent = err.message; } });
  }
  async function renderAdmins() {
    const [items, dealers] = await Promise.all([api('/admin-users'), api('/dealers')]);
    $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">10 / ACCESS CONTROL</span><h3>管理员与权限</h3><p>按角色分配后台能力。密码不会回显，只能通过重置或本人修改。</p></div><div class="toolbar"><button class="button primary-small" id="newAdmin">新增管理员</button></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>账号</th><th>显示名</th><th>角色</th><th>经销商</th><th>状态</th><th>更新时间</th><th></th></tr></thead><tbody id="adminRows">${items.map((item) => `<tr><td><code>${escape(item.username)}</code></td><td>${escape(item.display_name)}</td><td>${roleLabels[item.role] || item.role}</td><td>${escape(dealers.find((dealer) => dealer.id === item.dealer_id)?.name || '总部')}</td><td>${item.active ? '<span class="badge green">启用</span>' : '<span class="badge red">停用</span>'}</td><td>${fmt(item.updated_at)}</td><td><button class="button" data-admin-id="${item.id}">编辑</button></td></tr>`).join('') || '<tr><td colspan="7" class="empty">暂无管理员</td></tr>'}</tbody></table></div></div>`;
    $('#newAdmin').addEventListener('click', () => showAdmin(null, dealers)); $('#adminRows').addEventListener('click', (event) => { const button = event.target.closest('[data-admin-id]'); if (button) showAdmin(items.find((item) => String(item.id) === button.dataset.adminId), dealers); });
  }
  function showAdmin(item, dealers) {
    const roles = Object.entries(roleLabels); const backdrop = drawerShell(`<p class="eyebrow">ADMIN / ACCESS CONTROL</p><h3>${item ? '编辑管理员' : '新增管理员'}</h3><div class="edit-grid">${item ? `<label>账号<input value="${escape(item.username)}" disabled></label>` : input('账号', '', 'username')} ${input('显示名', item?.display_name || '', 'display_name')}<label>角色<select data-field="role">${roles.map(([value, label]) => `<option value="${value}" ${item?.role === value ? 'selected' : ''}>${label}</option>`).join('')}</select></label><label>经销商<select data-field="dealer_id"><option value="">总部</option>${dealers.map((dealer) => `<option value="${dealer.id}" ${item?.dealer_id === dealer.id ? 'selected' : ''}>${escape(dealer.name)}</option>`).join('')}</select></label>${input('密码（至少 12 位，编辑时留空不修改）', '', 'password', 'password')}<label class="check-line"><input type="checkbox" data-field="active" ${item?.active !== 0 ? 'checked' : ''}>启用账号</label></div><div class="save-bar"><button class="button primary-small" data-drawer-action="save-admin">保存管理员</button></div>`, 'min(680px,90vw)'); $('.drawer', backdrop).addEventListener('click', async (event) => { if (!event.target.closest('[data-drawer-action="save-admin"]')) return; try { const drawer = $('.drawer', backdrop); const payload = Object.fromEntries([...drawer.querySelectorAll('[data-field]')].map((el) => [el.dataset.field, el.type === 'checkbox' ? el.checked : el.value])); if (payload.dealer_id === '') payload.dealer_id = null; if (item) await patch(`/admin-users?id=${item.id}`, payload); else await post('/admin-users', payload); backdrop.remove(); toast('管理员资料已保存'); navigate('admins'); } catch (err) { toast(err.message, true); } });
  }
  async function renderSettings() {
    const items = await api('/settings');
    $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">11 / SYSTEM SECURITY</span><h3>系统与安全</h3><p>维护会话、登录限流、CSRF 和图片上传策略。高风险配置采用服务端范围校验。</p></div></div><div class="detail-grid"><div class="panel"><div class="panel-head"><h3>当前登录</h3><small>${escape(state.auth?.username || '')} · ${escape(roleLabels[state.auth?.role] || state.auth?.role || '')}</small></div><form id="passwordForm" class="upload-form"><h4>修改我的密码</h4><label>当前密码<input name="old_password" type="password" required></label><label>新密码<input name="new_password" type="password" minlength="12" required></label><label>确认新密码<input name="confirm_password" type="password" minlength="12" required></label><button class="button primary-small" type="submit">更新密码</button><p id="passwordError" class="error"></p></form></div><div class="panel"><div class="panel-head"><h3>安全策略</h3><small>仅允许维护预置键</small></div><div class="settings-list">${items.map((item) => `<form class="setting-row" data-setting-key="${escape(item.setting_key)}"><div><b>${escape(item.setting_key)}</b><small>${escape(item.description || '')}</small></div><input name="setting_value" value="${escape(item.setting_value)}" data-value-type="${escape(item.value_type)}"><button class="button" type="submit">保存</button></form>`).join('')}</div></div></div>`;
    $('#passwordForm').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const error = $('#passwordError'); if (form.get('new_password') !== form.get('confirm_password')) { error.textContent = '两次输入的新密码不一致'; return; } try { await post('/auth/password', { old_password: form.get('old_password'), new_password: form.get('new_password') }); toast('密码已更新，请重新登录'); } catch (err) { error.textContent = err.message; } });
    document.querySelectorAll('.setting-row').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); try { const inputEl = $('input', form); let value = inputEl.value; if (inputEl.dataset.valueType === 'json') value = JSON.parse(value); await post('/settings', { setting_key: form.dataset.settingKey, setting_value: value, value_type: inputEl.dataset.valueType }); toast('安全配置已保存'); } catch (err) { toast(err.message, true); } }));
  }
  function renderCatalogAudit(data) {
    const labels = { active_products: '在售产品', active_configurable: '在售可配置', duplicate_configurator_keys: '重复配置键', active_config_missing_types: '缺少门型', active_config_missing_dimensions: '缺少尺寸', active_config_missing_prices: '缺少产品价格', active_config_missing_option_prices: '缺少选配价格规则', active_config_missing_assets: '缺少产品素材', inactive_price_rules: '下架产品历史价格', price_unlinked_options: '价格未关联选配', price_unlinked_types: '价格未关联门型', options_missing_type_links: '选配缺少门型关联', inactive_product_options: '配置含停用选配', invalid_dimensions: '非法尺寸' };
    const riskKeys = new Set(['duplicate_configurator_keys', 'active_config_missing_types', 'active_config_missing_dimensions', 'active_config_missing_prices', 'active_config_missing_option_prices', 'active_config_missing_assets', 'price_unlinked_options', 'price_unlinked_types', 'options_missing_type_links', 'inactive_product_options', 'invalid_dimensions']);
    const infoKeys = new Set(['active_products', 'active_configurable', 'inactive_price_rules']);
    const summary = Object.entries(data.summary).map(([key, value]) => `<div class="metric ${riskKeys.has(key) && value ? 'audit-risk' : infoKeys.has(key) ? 'audit-info' : ''}"><small>${escape(labels[key] || key)}</small><strong>${value}</strong><em>${riskKeys.has(key) ? (value ? '需要处理或复核' : '通过') : infoKeys.has(key) ? (key === 'inactive_price_rules' ? '历史记录' : '当前统计') : (value ? '需要处理或复核' : '通过')}</em></div>`).join('');
    const issues = data.issues.map((item) => `<tr><td>${escape(labels[item.type] || item.type)}</td><td>${escape(item.name || item.id || '—')}</td><td>${escape(item.configurator_key || item.option_id || item.door_type_id || '—')}</td><td><span class="badge red">需处理</span></td></tr>`).join('');
    $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">12 / CATALOG CONSISTENCY</span><h3>产品一致性检查</h3><p>核对在售、可配置、门型尺寸、选配和价格规则是否指向同一个真实产品。</p></div><button class="button" id="refreshCatalogAudit">重新检查</button></div><div class="metric-grid audit-metrics">${summary}</div><div class="panel"><div class="panel-head"><h3>待处理问题</h3><small>${data.issues.length} 条</small></div><div class="table-wrap"><table class="data-table"><thead><tr><th>问题类型</th><th>产品 / 记录</th><th>配置键 / 引用</th><th>状态</th></tr></thead><tbody>${issues || '<tr><td colspan="4" class="empty">产品、配置和价格规则已全部对应</td></tr>'}</tbody></table></div></div>`;
    $('#refreshCatalogAudit').addEventListener('click', () => navigate('catalogAudit'));
  }
  async function renderSources(items) { const guide = await api('/design-guide').catch(() => null); $('#content').innerHTML = `<div class="page-head"><div><span class="section-code">07 / REFERENCE DOCUMENTS</span><h3>来源文档</h3><p>产品目录、PDF、配置器和图片资产的导入记录。</p></div></div>${guide ? `<section class="guide-board"><div class="guide-board-head"><div><span class="guide-kicker">YADILO PRODUCT DESIGN / 2026.07</span><h3>${escape(guide.title)}</h3><p>当前后台的产品结构、尺寸限制与 CMFP 管理字段以此手册为设计依据。</p></div><a class="button" href="./${guide.file_path}" target="_blank" rel="noreferrer">打开 PDF ↗</a></div><div class="guide-principles">${guide.principles.map((item, index) => `<div><b>0${index + 1}</b><span>${escape(item)}</span></div>`).join('')}</div><div class="guide-preview-grid">${guide.preview_pages.slice(0, 4).map((path) => `<img src="./${path}" alt="设计指导手册预览">`).join('')}</div></section>` : ''}<div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>文档</th><th>类型</th><th>路径</th><th>页数</th><th>导入时间</th></tr></thead><tbody>${items.map((item) => `<tr><td>${escape(item.title || '未命名')}</td><td>${escape(item.document_type)}</td><td><code>${escape(item.file_path)}</code></td><td>${item.page_count || '—'}</td><td>${fmt(item.imported_at)}</td></tr>`).join('') || '<tr><td colspan="5" class="empty">暂无来源文档</td></tr>'}</tbody></table></div></div>`; }
  function renderAudit(items) { $('#content').innerHTML = `<div class="page-head"><div><h3>操作日志</h3><p>记录产品、选配、价格、方案和咨询状态的后台修改。</p></div></div><div class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>时间</th><th>用户</th><th>操作</th><th>对象</th><th>详情</th></tr></thead><tbody>${items.map((item) => `<tr><td>${fmt(item.created_at)}</td><td>${escape(item.username || 'website')}</td><td>${escape(item.action)}</td><td>${escape(item.entity_type)} / ${escape(item.entity_id)}</td><td><code>${escape(item.detail_json)}</code></td></tr>`).join('') || '<tr><td colspan="5" class="empty">暂无日志</td></tr>'}</tbody></table></div></div>`; }
  document.addEventListener('click', (event) => { const go = event.target.closest('[data-go]'); if (go) navigate(go.dataset.go); });
  boot().catch((error) => { $('#loginError').textContent = error.message; });
})();
